### ISSUE TITLE
setting theme.blingbling table

### ISSUE THREAD

**Issue by bjne** [cedlemo/blingbling#37]
I dont have any success setting values in this table, seems they are not picked up
by blingbling widgets. Using awesome 3.5 and blingbling from git

**Comment by cedlemo** [comment]
Show me your rc.lua and your theme.lua please.

**Comment by bjne** [comment]
I managed to solve the issue, seems the reason was that I require
"blingbling"
before setting theme.blingbling variables. Perhaps it is possible to work
around
this by not initializing superproperties until "used"?

-- 
Bj(/)rnar

**Comment by cedlemo** [comment]
Yes, maybe you are right.

In all rc.lua I have done or used blingbling and the theme capabilities, I always add the line `local blinbling = require("blingbling")` after `beautiful.init`. For now, I will make some tests and try to find a solution.

**Comment by cedlemo** [comment]
@bjne,
I finally managed to find some time (and I fell really sorry for not being able to do this earlier).
The commit ca9ea48beb57b0b16541c867509bc816bf735894 fix (or at least provide an acceptable solution I think) to your request.

Knowing how the beautiful module works, I can't do better:

If you want to configure some style properties in your theme file, you have two solutions:

*    `require('blingbling')` after having initialized `beautiful` in your rc.lua (with `beautiful.init`)
*    `require('blingbling')` before the initialization of beautiful but in this case you have to add this line before any use of the widgets:

    blingbling.superproperties.init(the_path_of_the_theme_file)

Look in the example : 

https://github.com/cedlemo/blingbling/blob/master/config_example/japanese2/theme.lua

**Comment by cedlemo** [comment]
.
